"""
Runtime data import service.

Imports JSON snapshots generated by `core.sync.export_service`.
"""

from __future__ import annotations

import json
from pathlib import Path

from api_server.storage import repo as default_repo


def load_import_payload(file_path: str) -> dict:
    source = Path(file_path).expanduser()
    if not source.is_absolute():
        source = Path.cwd() / source
    if not source.exists():
        raise FileNotFoundError(f"import file not found: {source}")
    payload = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or not isinstance(payload.get("data"), dict):
        raise ValueError("invalid import payload: expected top-level {data:{...}}")
    return payload


def apply_import_payload(payload: dict, overwrite: bool = True, repository=None) -> dict:
    repo = repository or default_repo
    data = payload.get("data", {})
    imported = 0
    skipped = 0
    for key, value in data.items():
        if not overwrite and repo.kv_get(key, None) is not None:
            skipped += 1
            continue
        repo.kv_set(key, value)
        imported += 1
    return {
        "total": len(data),
        "imported": imported,
        "skipped": skipped,
        "overwrite": overwrite,
    }


def import_from_file(file_path: str, overwrite: bool = True, repository=None) -> dict:
    payload = load_import_payload(file_path)
    result = apply_import_payload(payload, overwrite=overwrite, repository=repository)
    result.update(
        {
            "file_path": str(Path(file_path).expanduser()),
            "schema_version": payload.get("schema_version", ""),
            "exported_at": payload.get("exported_at", ""),
        }
    )
    return result
