@echo off
setlocal EnableExtensions
cd /d "%~dp0"

if not defined FINQUANTA_ENV (
  set "FINQUANTA_ENV=dev"
)
if not defined FINQUANTA_API_HOST (
  set "FINQUANTA_API_HOST=0.0.0.0"
)
if not defined FINQUANTA_API_PORT (
  set "FINQUANTA_API_PORT=9000"
)
if not defined FINQUANTA_DB_BACKEND (
  set "FINQUANTA_DB_BACKEND=sqlite"
)
if not defined FINQUANTA_SQLITE_PATH (
  set "FINQUANTA_SQLITE_PATH=data_cache\quant.db"
)
if not defined FINQUANTA_CORS_ORIGINS (
  set "FINQUANTA_CORS_ORIGINS=*"
)
if not defined FINQUANTA_SNAPSHOT_CACHE_TTL (
  set "FINQUANTA_SNAPSHOT_CACHE_TTL=120"
)
if not defined FINQUANTA_OPENCLAW_GATEWAY_ENABLED (
  set "FINQUANTA_OPENCLAW_GATEWAY_ENABLED=1"
)
if not defined FINQUANTA_OPENCLAW_GATEWAY_BASE (
  set "FINQUANTA_OPENCLAW_GATEWAY_BASE=http://127.0.0.1:18789"
)
if not defined FINQUANTA_API_AUTOSTART_DAEMON (
  set "FINQUANTA_API_AUTOSTART_DAEMON=1"
)
if not defined FINQUANTA_DAEMON_BOARDS (
  set "FINQUANTA_DAEMON_BOARDS=人工智能,芯片,量子科技"
)

echo Starting FinQuanta API...
echo   API_HOST=%FINQUANTA_API_HOST%
echo   API_PORT=%FINQUANTA_API_PORT%
echo   OPENCLAW_GATEWAY_ENABLED=%FINQUANTA_OPENCLAW_GATEWAY_ENABLED%
echo   OPENCLAW_GATEWAY_BASE=%FINQUANTA_OPENCLAW_GATEWAY_BASE%
echo   API_AUTOSTART_DAEMON=%FINQUANTA_API_AUTOSTART_DAEMON%
echo   DAEMON_BOARDS=%FINQUANTA_DAEMON_BOARDS%
python -m uvicorn api_server.main:app --host "%FINQUANTA_API_HOST%" --port "%FINQUANTA_API_PORT%"
