apiVersion: 1
datasources:
  - name: FinQuanta Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
  - name: FinQuanta Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
  - name: FinQuanta Infinity
    uid: infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      allowedHosts:
        - "*"
